### ISSUE TITLE
Integration with OSMeta

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#101]
The classes don't have SEO titles and descriptions available at the moment

**Comment by billtomczak** [comment]
I assume we want title/meta for at least course and lesson layers. Depending on the final outcome of the pathways discussion, probably there as well.

Rather than have separate meta fields, would this make sense?

Course pages: course title / some subset of the description
Lesson pages: course title + lesson title / same as for course

Or if you would rather have separate fields, I could pre-populate them with this information since there isn't any other source for it.

**Comment by stevejburge** [comment]
Yes, course, lesson and perhaps pathways, please

We could do this programatically, but manual is always better if possible.

Pre-populating sounds good.

**Comment by billtomczak** [comment]
Using a separate branch for this https://github.com/OSTraining/OSCampus/tree/meta-data

I've implemented an initial set of proposals for titles and meta descriptions at ghostexplained.com. I've pre-populated them from their description fields.

pathways and courses seem pretty straightforward, but I don't see any reasonable means of creating a default for them.

Next step will be to create the plugin for OSMeta for easier editing of OSCampus metadata.

**Comment by stevejburge** [comment]
Wonderful, thanks Bill. With 2600 videos to go back and add metadata to, this will be a huge help.

**Comment by htmgarcia** [comment]
It would be cool to[ integrate the video too](http://wistia.com/doc/video-seo).
![wistia](http://embed.wistia.com/deliveries/6d0d9cf14d2f214a6e46e9cac6cad9da678f84ae.png)

**Comment by billtomczak** [comment]
nice! I'll see if I can incorporate this.

**Comment by billtomczak** [comment]
If I understand this correctly, we should already be seeing this on ostraining.com. Says it's automatic for standard embeds, which is what we're using.

**Comment by htmgarcia** [comment]
The most of the videos are private, so, those won't be displayed and I guess we don't want to - lol

**Comment by billtomczak** [comment]
Well, but for the public ones. There are a few of those

**Comment by nicksavov** [comment]
I'm not seeing a preview at https://www.google.com/?gws_rd=ssl#q=site:https:%2F%2Fwww.ostraining.com%2Fclasses%2Fwordpress%2Fwp-beginner%2Fthe-dashboard%2F

**Comment by billtomczak** [comment]
yeah - not seeing anything there either. If we want to pursue this, let's make it a new issue. I think we have other priorities at the moment and I'll have to look into this. OSCampus uses OSWistia for video rendering so may turn out to be an issue addressed there.

**Comment by htmgarcia** [comment]
Agree!

**Comment by nicksavov** [comment]
+1, https://github.com/OSTraining/OSCampus/issues/155

**Comment by billtomczak** [comment]
I think we're done with this issue. I'm not going to work on an OSMeta integration as the defaulting system I've created seems to make everyone happy.

@stevejburge - sounds like you're planning to add footers too all the lessons? Would it make sense to use those for a default meta-description if available? 

Otherwise, as I mentioned in the meeting, if you find you need a bulk method to update lesson metadata, let me know. Creating something quick and simple in the admin would be much easier than an OSMeta integration at this time.

**Comment by stevejburge** [comment]
Sounds good. Maybe we wait for @andergmartins to improve OSMeta and then do the integration. No need to do something custom yet.

Yes, I hope to add a footer to all lessons. Can we perhaps add some way of indicating which lessons have a description?
