### ISSUE TITLE
Menu links to individual classes

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#141]
![screen shot 2016-02-10 at 10 50 19 am](https://cloud.githubusercontent.com/assets/3868028/12952337/2f3e425a-cfe4-11e5-967f-05888a793bb4.png)

**Comment by nicksavov** [comment]
As a work around, you can do a menu item of type external URL and add the direct URL to the class. Since the class URLs won't change much, if at all, this should be a good work around.

**Comment by stevejburge** [comment]
True, but long-term it should be a feature, right?

**Comment by nicksavov** [comment]
Yes, I think so. I think it will be tricky to implement and we'll first have to figure out how we want pathways and individual classes to work, URL wise. 

For example, if we had a menu item to the PHP class. What should its alias be?
- php
- coding/php (where coding is the pathway)
- classes/coding/php (where classes is the alias for all the pathways and coding is the pathway)

And what happens when we add another pathway, say Joomla Development, that includes the PHP class too?
- joomla-dev/php

I think it goes back to the conundrum of https://github.com/OSTraining/OSCampus/issues/43

**Comment by billtomczak** [comment]
We need to have a careful, in depth discussion about url segment structure, pathways, navigation, menuing and whatever else I'm not immediately thinking of. 

We depend on external urls a lot in a lot of places on ostraining.com and I've come to accept their inevitability so at least for now, it makes sense that this would be the way to approach it.

I may have gone down a completely wrong path in my thinking and I'm thrashing about in a thicket. But here's the way things look to me...

The fewer the url segments the more there is an issue with url conflicts. We've already seen this by taking out the module segment that guru used causing some lesson alias conflicts. Fortunately, as @stevejburge saw, this wasn't too bad to fix. 

We _could_ safely take out the pathway segment, since it looks like every single course does have a unique alias at the moment. I'd want to start enforcing that in the admin UI.

If we take out the menu anchor for pathways (/classes/) now course aliases must be guaranteed to provide a unique base segment throughout the site. And lots of non-class urls are being generated automatically via article categories among an unknown (to me) number of other possibilities for auto-generated url segments.

Without a menu anchor, the Joomla router has no clue that it needs to ask OSCampus to translate it. There's no way to distinguish /wordpress (as an OSCampus pathway) from /wordpress as a Joomla category. Maybe not an actual example from the site, but hopefully you see my point. It's just some text referring to _something_

Using /classes/ as a known OSCampus menu for listing pathways, I can stack segments as the user drills down. First segment gives me the pathway (/classes/wordpress), Second gives me the class (/classes/wordpress/why), Third the lesson. Without that menu anchor I have no idea this is an OSCampus item.

Unless we allow creating menus on classes directly (and/or lessons). If we do that, we now have at least two urls for a menued class:

`/classes/wordpress/why`

and maybe something like

`/why-wordpress`

And if this class appears in more than one pathway, it has three urls.

So..... @nicksavov, @stevejburge -- I'd love to have a meeting to untangle all this. Since the way we end up implementing pathways could have an effect on OSTeammate, would be good to have @andergmartins available for that meeting.

btw - I have no doubt this was why mambo originally included id numbers in sef urls. No one was thinking SEO at the time and it guaranteed no url segment conflicts anywhere.

**Comment by andergmartins** [comment]
I agree with @billtomczak about using the menu anchor, trying to have as more segments as we can for primary urls. Maybe I'm missing something, but to be honest I don't see problems in having multiple pages for the same content, as long as we use the canonical url tag. We can have multiple url patterns, just need to make sure to have the correct canonical url set.

**Comment by stevejburge** [comment]
Sure thing, a meeting sounds good.

I don't often push back on these things, but unique URLs is somewhere I'm going to be insistent. We do need unique URLs for each class.

In SEO terms, canonical terms are like a band-aid ... an attempt to fix an bad situation. It's far better not get into a bad situation in the first place.

I'm not picky as to what the URLs are. They just need to be unique.

**Comment by billtomczak** [comment]
We should definitely discuss all this asap. It's become a major issue with wide ranging affects.

**Comment by stevejburge** [comment]
OK, 3pm EST today?

**Comment by billtomczak** [comment]
Good for me

**Comment by andergmartins** [comment]
+1

**Comment by nicksavov** [comment]
+1

**Comment by billtomczak** [comment]
Resolved by recent url changes dc6b036f1da43b86c4a365628534e07854c1dde8...bde2a96039961aae334ea952c1da13ea326ae67b
