### ISSUE TITLE
Missing column 'checked_out' in #__oscampus_modules

### ISSUE THREAD

**Issue by puckett15** [OSTraining/OSCampus#142]
![Error Install Message](https://cloud.githubusercontent.com/assets/13893942/12953485/4a1741e8-cfe0-11e5-80ba-932668a29f2c.png)

On initial install of OSCampus, it is looking for the column 'checked_out' in table #__oscampus_modules and it can't find it because it was never created. So on first install, oscampus won't install correctly (unless you were to go in and create that column).

**Comment by htmgarcia** [comment]
@nicksavov's commit fixed the issue.
Feel free to reopen if needed.

**Comment by htmgarcia** [comment]
I re-read the column 'checked_out' in table #__oscampus_modules needs to be created

**Comment by nicksavov** [comment]
I think it's supposed to be removed. It was added in beta 3-ish:
https://github.com/OSTraining/OSCampus/blob/cb7cb2e56d51e534932f895bcbd4cd812c36b3f7/src/admin/sql/updates/mysql/0.0.1b3.sql

and removed in beta 12-ish:
https://github.com/OSTraining/OSCampus/blob/cb7cb2e56d51e534932f895bcbd4cd812c36b3f7/src/admin/sql/updates/mysql/0.0.1b12.sql

It's probably because it just needs to be a title and is only created in the lessons area.

**Comment by nicksavov** [comment]
Confirmed:
https://github.com/OSTraining/OSCampus/commit/c581134179a55c84c69ba301fb9d52fd77f8fa5e

**Comment by billtomczak** [comment]
@nicksavov - you did good :)

Just not far enough. See 92026dd43bb3f20ea0d0e84cabd00afba9a4b66e

**Comment by nicksavov** [comment]
Touché :D
