### ISSUE TITLE
Small UI fix on Lessons page

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#191]
Would it make sense to remove "Released", "Difficulty" and perhaps "ID"?

This might allow us to make room for statistics here instead, such as number of views.

![screen shot 2016-03-11 at 3 31 02 pm](https://cloud.githubusercontent.com/assets/3868028/13714744/7768b0ac-e79e-11e5-87b1-15a13fe483a6.png)
 to make more room?

**Comment by billtomczak** [comment]
I don't like removing the id column. That often comes in handy for tracking down problems.

But otherwise - yes, no problem!

**Comment by stevejburge** [comment]
Thanks. I'd love us to start pulling out stats and putting them into the UI. They help track down problems ...

Why is no-one watching this video?
Why do 100% of people get this quiz question wrong?

**Comment by nicksavov** [comment]
Fixed with https://github.com/OSTraining/OSCampus/commit/f3eb3ff082e7f5634ad63aeaae26ba01519d8d21 :) Since it's just a layout change, I went ahead and implemented on the site already.

Since the original issue is resolved, let's go ahead and close this one. I've opened up an analytics task at https://github.com/OSTraining/OSCampus/issues/192
