### ISSUE TITLE
/classes/ and /pathways/

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#198]
I feel like we're pretty close to this, but can we complete the process of creating a different view for /classes/ and /pathways/?

/classes/ would list individual classes
/pathways/ would list pathways

**Comment by billtomczak** [comment]
That's a huge change to our SEO. We have half of that that right now. /classes lists pathways.

For lists of classes we now have 

/new-classes
/myclasses 
/component/oscampus/search
   (since there isn't a specific menu page created for it) for filtered search results

What would a new list of classes be?

**Comment by stevejburge** [comment]
Ah, you're saying that would break our URLs?

If so, the actual URLs of /classes/ and /pathways/ don't matter, so much as the fact that we show the difference

**Comment by billtomczak** [comment]
Right. So the remaining question for me is are those three class lists all we need at the moment? I don't think we really need a url with an unfiltered list of every class. Although the search landing page would provide that with no filters applied. :)

Otherwise, this all still maintains the convention that all classes always show up on the /class base url.

**Comment by billtomczak** [comment]
and btw - the search page can (and perhaps should) be set up on a menu. You can make the url whatever you want it to be :)

**Comment by stevejburge** [comment]
Ok, great. Yes, I think three are a great way to start.

When it comes to the list of classes, perhaps we show the classes that the student took most recently, or something like that?

**Comment by billtomczak** [comment]
That's exactly what myclasses provides now. And with the completion filter set, the search landing page would provide the same thing.

Something that needs to be added to all these views is sortable columns at least and possibly pagination as well.

**Comment by stevejburge** [comment]
Ah, you're right! Yes, let's add the columns and pagination. Then we can publish My Classes to the main menu. 

Perhaps the default sorting is "Last visited"? The most recent on top?

**Comment by billtomczak** [comment]
Yes - each view can have it's own defaults:

search results: class title ascending
myclasses: last visit descending
new-classes: release date ascending

**Comment by billtomczak** [comment]
I think that's what I'm using right now. I should be :)

**Comment by nicksavov** [comment]
Looks like the desired effects are already available, is that correct?

**Comment by htmgarcia** [comment]
Agree. Each class has a unique permalink.
