### ISSUE TITLE
Search for individual classes

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#246]
This is on the Google Doc, but doesn't appear to be here in the tracker (sorry if I missed it).
> Can’t search for individual classes. “Firebug” should pull up the “CSS for Joomla” class

**Comment by billtomczak** [comment]
There are a number of issues related to the search module which has been going through some massive changes from the start. Most of the following relate to this. I'd love to see some consolidation!

#105, #187, #195, #197, #198, #200, #202, #204, #216, #219

**Comment by nicksavov** [comment]
OK, looks like those are separate from this one though. The issue for this one appears to be that when you search for "firebug" it brings up two results:
- Drupal 8 Layout and Theming
- Joomla 2 Template Design

But it's missing the following class, which has "FireBug" as the second lesson:
- https://www.ostraining.com/class/jcss/
- https://www.ostraining.com/class/jcss/firebug/

For the consolidation part, I just recently created a label for "Search". I'll go ahead and add it to all those items and that should provide the consolidation that's needed, while at the same time allowing us to tackle the issues separately in different milestones.

**Comment by billtomczak** [comment]
It's all about the search module which is involved in searching _for individual classes_. That is an issue about a specific problem with it.

Besides, there's another radical change coming up that will possibly make half of these issues irrelevant. It's difficult to tell because it's been a rapidly moving target.

Bottom line: The search module is about searching for individual classes. Among other things and all those issues are related to it and may or may not be relevant with the new changes coming up.

**Comment by billtomczak** [comment]
Moving forward with the new plan for searches:

1) The search module will *always* take the user to the search results page.
2) Various class/pathway lists will not be filtered at this stage
3) The filter fields in the module will be, per @stevejburge via slack chat

```
Just untangling those discussions we’ve been having
I wonder if the search box should be like this?

- Search field
- Topic
- 3 checkboxes … Pathway / Class / Video
```

Please confirm, I'm converging on this solution right now.

**Comment by nicksavov** [comment]
Looks good. For 3, I wouldn't search "within" Pathways if that makes sense. If someone selects only Pathway, it shouldn't look for a class or less with that search criteria. Same for class.

**Comment by billtomczak** [comment]
The problem with that is 'Topic' is a tag search. Since pathways are not directly tagged (nor do I think they should be), the only way to find pathways with a selected tag is to look at the classes in the pathway. Having gone that far, it would seem odd to me not to search classes for the free text as well.

**Comment by nicksavov** [comment]
I think from a user perspective, if just Pathways is selected, the user would expect to see just pathways (rather than content within them), but I might be mistaken.

**Comment by billtomczak** [comment]
So you're actually talking about what results to show. That can be easily arranged. After the most recent discussions, the search page is going to be revamped a bit to handle showing pathways, classes and individual lessons (videos).

So the checkboxes would be additive? What happens if no checkboxes are selected? No results, or same as all three selected?

This also raises the issue of search display - all mixed together or separated by type?

**Comment by nicksavov** [comment]
OK, great.

Probably the same as all three.

Good question :) Probably by type.

**Comment by billtomczak** [comment]
Closing for this phase of things. I'm sure there will be more issues. Please tag with the search label.
