### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#290]
See:
https://secure.helpscout.net/conversation/251329687/39415/?folderId=852196

**Comment by billtomczak** [comment]
re: 2. The language files all have spacing before and after the = between 
the key and the string.
remove spacing before and after = for all 250 keys/strings.

There is no clear standard for ini files in this regard. Since php recognizes and Joomla requires the use of quotes for values, there are no whitespace issues. See also examples used at  http://www.w3schools.com/php/func_filesystem_parse_ini_file.asp

\3. Language files are not added to core folders. They only get installed 
in the component language subfolders. Would be logic to also have them 
added to core folders at install.
**Not loaded** : JROOT\administrator/language/en-GB/en-GB.com_oscampus.ini

This is the preferred design. Since Joomla 2.5+ language files do not need to be in the core folders.   Duplicating them in the core would create potential confusion. Also note that language override strings are designed to accommodate this arrangement. We follow the preferred policy of avoiding any modification of core folders and files wherever possible.
